name: Deploy Nuxt 3 App to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Clean remote directory
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.RASPI_SSH_HOST }}
        username: ${{ secrets.RASPI_SSH_USERNAME }}
        key: ${{ secrets.RASPI_SSH_KEY }}
        script: |
          if [ -d "/home/${{ secrets.RASPI_SSH_USERNAME }}/pdmoonblog/nuxt-app" ]; then
            rm -rf /home/${{ secrets.RASPI_SSH_USERNAME }}/pdmoonblog/nuxt-app
          fi

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.RASPI_SSH_HOST }}
        username: ${{ secrets.RASPI_SSH_USERNAME }}
        key: ${{ secrets.RASPI_SSH_KEY }}
        source: ./.output/
        target: /home/${{ secrets.RASPI_SSH_USERNAME }}/pdmoonblog/nuxt-app/

    - name: Copy ecosystem.config.cjs via SSH
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.RASPI_SSH_HOST }}
        username: ${{ secrets.RASPI_SSH_USERNAME }}
        key: ${{ secrets.RASPI_SSH_KEY }}
        source: ./ecosystem.config.cjs
        target: /home/${{ secrets.RASPI_SSH_USERNAME }}/pdmoonblog/nuxt-app/

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.RASPI_SSH_HOST }}
        username: ${{ secrets.RASPI_SSH_USERNAME }}
        key: ${{ secrets.RASPI_SSH_KEY }}
        script: |
          cd /home/${{ secrets.RASPI_SSH_USERNAME }}/pdmoonblog/nuxt-app/
          pm2 stop ecosystem.config.cjs || true
          pm2 delete ecosystem.config.cjs || true
          pm2 start ecosystem.config.cjs
